// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InitWorldContract.proto

package com.vv.personal.grpc.proto;

public interface HelloResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vv.personal.grpc.proto.HelloResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
