// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InitWorldContract.proto

package com.vv.personal.grpc.proto;

public final class InitWorldContract {
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_vv_personal_grpc_proto_HelloRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_vv_personal_grpc_proto_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_vv_personal_grpc_proto_HelloResponse_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_vv_personal_grpc_proto_HelloResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\027InitWorldContract.proto\022\032com.vv.person" +
                    "al.grpc.proto\"3\n\014HelloRequest\022\021\n\tfirstNa" +
                    "me\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\" \n\rHelloRespo" +
                    "nse\022\017\n\007message\030\002 \001(\t2q\n\014HelloService\022a\n\010" +
                    "SayHello\022(.com.vv.personal.grpc.proto.He" +
                    "lloRequest\032).com.vv.personal.grpc.proto." +
                    "HelloResponse\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    }, assigner);
    internal_static_com_vv_personal_grpc_proto_HelloRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_vv_personal_grpc_proto_HelloRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_vv_personal_grpc_proto_HelloRequest_descriptor,
            new java.lang.String[]{"FirstName", "LastName",});
    internal_static_com_vv_personal_grpc_proto_HelloResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_com_vv_personal_grpc_proto_HelloResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_vv_personal_grpc_proto_HelloResponse_descriptor,
            new java.lang.String[]{"Message",});
  }

  private InitWorldContract() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
